<?php
get_header();
$services = get_posts( array( 'post_type' => 'mirall_service', 'post_status' => 'publish', 'numberposts' => 4, 'orderby' => 'menu_order', 'order' => 'ASC' ) );
$fallback_services = array(
	array( 'رنگ و لایت', 'بالیاژ، آمبره، هایلایت، اصلاح رنگ و انتخاب تناژ.', '✦', 'balayage-warm.jpg' ),
	array( 'میکاپ و عروس', 'طراحی چهره، میکاپ حرفه‌ای و انتخاب مدل از بروشور.', '❀', 'makeup.jpg' ),
	array( 'خدمات ناخن', 'کاشت، ژل، لمینت، ترمیم و طراحی ظریف ناخن.', '◇', 'caramel-highlight.jpg' ),
	array( 'مو و ابرو', 'هیرکات، براشینگ، لیفت ابرو و میکروبلیدینگ.', '⌁', 'balayage-girly.jpg' ),
);
	$service_images = array( 'balayage-warm.jpg', 'makeup.jpg', 'caramel-highlight.jpg', 'balayage-girly.jpg' );
	$instagram_works = mirall_instagram_works();
	$instagram_videos = array_values( array_filter( $instagram_works, function ( $work ) { return 'video' === $work['type']; } ) );
?>
<main id="main">
	<section class="hero" id="home">
		<div class="hero-slider" aria-label="نمونه کارهای منتخب میرال">
			<?php $hero_title = mirall_option( 'hero_title', 'زیبایی تو، امضای توست' ); $hero_parts = array_map( 'trim', explode( '،', $hero_title, 2 ) ); ?>
			<article class="hero-slide active"><img class="hero-bg" src="<?php echo mirall_image_option( 'hero_image_1', mirall_asset( 'balayage-warm.jpg' ) ); ?>" alt="بالیاژ گرم میرال"><div class="hero-copy reveal"><span class="eyebrow">MIRALL BEAUTY · FERESHTEH</span><h1><?php echo esc_html( $hero_parts[0] ); ?><?php if ( isset( $hero_parts[1] ) ) : ?>،<br><em><?php echo esc_html( $hero_parts[1] ); ?></em><?php endif; ?></h1><p>رنگ و لایت حرفه‌ای، میکاپ و خدمات زیبایی در فضایی آرام و دقیق؛ با انتخاب مدل پیش از رزرو.</p><div class="hero-actions"><button class="button open-booking">رزرو آنلاین نوبت</button><a class="button button-ghost" href="#portfolio">دیدن نمونه‌کارها</a></div></div></article>
			<article class="hero-slide"><img class="hero-bg" src="<?php echo mirall_image_option( 'hero_image_2', mirall_asset( 'makeup.jpg' ) ); ?>" alt="میکاپ میرال"><div class="hero-copy"><span class="eyebrow">MAKEUP · SIGNATURE LOOK</span><h2>میکاپی که<br><em>شبیه خودت می‌ماند</em></h2><p>سبک دلخواهت را در بروشور انتخاب کن و برای مشاوره تخصصی وقت بگیر.</p><div class="hero-actions"><button class="button open-booking">انتخاب مدل</button><a class="button button-ghost" href="#services">خدمات میکاپ</a></div></div></article>
			<article class="hero-slide"><img class="hero-bg" src="<?php echo mirall_image_option( 'hero_image_3', mirall_asset( 'balayage-warm.jpg' ) ); ?>" alt="بالیاژ میرال"><div class="hero-copy"><span class="eyebrow">COLOR · CUT · CARE</span><h2>رنگی هماهنگ با<br><em>پوست و استایل تو</em></h2><p>مشاوره رنگ، انتخاب تناژ و اجرای ظریف با توجه به سلامت مو.</p><div class="hero-actions"><button class="button open-booking">رزرو مشاوره رنگ</button><a class="button button-ghost" href="#portfolio">دیدن نتیجه‌ها</a></div></div></article>
			<div class="slider-controls"><button data-dir="prev" aria-label="اسلاید قبلی">‹</button><div class="slider-dots"></div><button data-dir="next" aria-label="اسلاید بعدی">›</button></div>
		</div>
		<aside class="hero-card reveal"><span>رزرو هوشمند میرال</span><strong>مدل دلخواهت را انتخاب کن</strong><p>خدمت، مدل و زمان مناسب را ببین و درخواست نوبت را ثبت کن.</p><button class="text-button open-booking">شروع رزرو ←</button></aside>
	</section>
	<section class="trust-strip"><div><span>۰۱</span><strong>مشاوره پیش از اجرا</strong><small>انتخاب متناسب با چهره</small></div><div><span>۰۲</span><strong>رزرو مرحله‌ای</strong><small>خدمت، مدل، زمان</small></div><div><span>۰۳</span><strong>نمونه‌کار واقعی</strong><small>منتخب صفحه رسمی میرال</small></div><div><span>۰۴</span><strong>دسترسی آسان</strong><small>فرشته، مجتمع داریوش</small></div></section>
	<section class="about section" id="about"><div class="about-visual reveal"><img src="<?php echo mirall_asset( 'caramel-highlight.jpg' ); ?>" alt="نمونه رنگ و لایت میرال"><div class="stamp">Mirall<br><small>Beauty Center</small></div></div><div class="section-copy reveal"><span class="eyebrow">درباره میرال</span><h2>جایی برای نسخهٔ <em>زیباتر خودت</em></h2><p>در میرال هر انتخاب از مشاوره شروع می‌شود. فرم چهره، تناژ پوست، سبک شخصی و سلامت مو کنار هم دیده می‌شوند تا نتیجه، زیبا و در عین حال طبیعی باشد.</p><p>مدل دلخواهت را از بروشور انتخاب کن و درخواست نوبتت را ثبت کن؛ پذیرش میرال پس از بررسی، زمان مناسب را با تو هماهنگ می‌کند.</p><div class="signature">Mirall Beauty <small>فرشته، تهران</small></div><button class="button open-booking">مشاوره و رزرو</button></div></section>
	<section class="services section" id="services"><div class="section-heading"><span class="eyebrow">خدمات میرال</span><h2>برای هر حال‌وهوای تو،<br><em>یک انتخاب دقیق</em></h2><p>از رنگ و لایت تا میکاپ، ناخن، مو، ابرو و مژه؛ انتخابت را با مشاوره شروع کن.</p></div><div class="service-grid">
	<?php if ( $services ) : foreach ( $services as $index => $service ) : ?>
		<article class="service-card reveal <?php echo 1 === $index ? 'featured' : ''; ?>"><img class="service-photo" src="<?php echo mirall_asset( $service_images[ $index % count( $service_images ) ] ); ?>" alt=""><div class="service-card-body"><span class="service-no">0<?php echo esc_html( (string) ( $index + 1 ) ); ?></span><div class="service-icon">✦</div><h3><?php echo esc_html( get_the_title( $service ) ); ?></h3><p><?php echo esc_html( wp_trim_words( $service->post_content, 18 ) ); ?></p><button class="text-button open-booking" data-service="<?php echo esc_attr( get_the_title( $service ) ); ?>">رزرو این خدمت ←</button></div></article>
	<?php endforeach; else : foreach ( $fallback_services as $index => $service ) : ?>
		<article class="service-card reveal <?php echo 1 === $index ? 'featured' : ''; ?>"><img class="service-photo" src="<?php echo mirall_asset( $service[3] ); ?>" alt=""><div class="service-card-body"><span class="service-no">0<?php echo esc_html( (string) ( $index + 1 ) ); ?></span><div class="service-icon"><?php echo esc_html( $service[2] ); ?></div><h3><?php echo esc_html( $service[0] ); ?></h3><p><?php echo esc_html( $service[1] ); ?></p><button class="text-button open-booking" data-service="<?php echo esc_attr( $service[0] ); ?>">رزرو این خدمت ←</button></div></article>
	<?php endforeach; endif; ?>
	</div></section>
	<section class="lookbook section" id="portfolio"><div class="section-heading compact"><span class="eyebrow">نمونه‌کارهای منتخب</span><h2>بروشور زیبایی <em>میرال</em></h2><p>منتخبی از تصاویر و ریل‌های عمومی صفحه رسمی میرال.</p></div><div class="filter-bar"><button class="active" data-filter="all">همه</button><button data-filter="hair">رنگ و مو</button><button data-filter="makeup">میکاپ</button></div><div class="portfolio-grid">
		<?php foreach ( array_slice( $instagram_works, 0, 8 ) as $index => $work ) : ?><article class="portfolio-item instagram-work-card <?php echo 0 === $index ? 'tall' : ''; ?>" data-cat="<?php echo esc_attr( $work['category'] ); ?>" data-title="<?php echo esc_attr( $work['title'] ); ?>"><button type="button" class="portfolio-image-button" aria-label="نمایش <?php echo esc_attr( $work['title'] ); ?>"><img loading="lazy" src="<?php echo esc_url( $work['image'] ); ?>" alt="<?php echo esc_attr( $work['title'] ); ?>، نمونه‌کار میرال"><em class="media-badge"><?php echo 'video' === $work['type'] ? '▶ ریل' : 'تصویر'; ?></em><span><small><?php echo esc_html( $work['label'] ); ?></small><strong><?php echo esc_html( $work['title'] ); ?></strong></span></button><a class="portfolio-source" href="<?php echo esc_url( $work['url'] ); ?>" target="_blank" rel="noopener">دیدن منبع اصلی ↗</a></article><?php endforeach; ?>
	</div><p class="portfolio-source-note">منبع: <a href="https://www.instagram.com/mirall_beauty_center/" target="_blank" rel="noopener">@mirall_beauty_center</a></p></section>
	<section class="before-after section" id="before-after"><div class="ba-copy"><span class="eyebrow">قبل و بعد</span><h2>جزئیات تغییر را <em>با دقت ببین</em></h2><p>این یک جفت‌تصویر هماهنگ از یک مدل و یک قاب است؛ نوار را حرکت بده تا تغییر بافت و درخشش مو را ببینی.</p><span class="editorial-note">تصویرسازی نمایشی · قابل جایگزینی با جفت‌تصویر واقعی از پنل</span><button class="button open-booking">رزرو مشاوره</button></div><div class="comparison" style="--position:52%"><img class="comparison-before" src="<?php echo mirall_asset( 'before-hair.jpg' ); ?>" alt="پیش از ترمیم و بالیاژ"><div class="comparison-after"><img src="<?php echo mirall_asset( 'after-hair.jpg' ); ?>" alt="پس از ترمیم و بالیاژ"></div><input type="range" min="0" max="100" value="52" aria-label="مقایسه قبل و بعد"><div class="comparison-line"><span>↔</span></div><b class="label-before">قبل</b><b class="label-after">بعد</b></div></section>
	<section class="video-reels section"><div class="section-heading compact"><span class="eyebrow">ویدیوهای میرال</span><h2>نتیجه‌ها را <em>در حرکت ببین</em></h2><p>منتخبی از ریل‌های صفحه رسمی میرال — مستقیم و لوکال، همین‌جا پخش کن.</p></div><div class="video-grid"><?php foreach ( array_slice( $instagram_videos, 0, 4 ) as $video ) : ?><article class="video-card local-video-card"><div class="video-frame" data-title="<?php echo esc_attr( $video['title'] ); ?>">
	<?php if ( ! empty( $video['video_file'] ) ) : ?>
		<video class="local-reel" preload="metadata" playsinline <?php echo $video['poster'] ? 'poster="' . esc_url( $video['poster'] ) . '"' : ''; ?> src="<?php echo esc_url( $video['video_file'] ); ?>"></video>
		<button type="button" class="play-mark video-toggle" aria-label="پخش ویدیوی <?php echo esc_attr( $video['title'] ); ?>">▶</button>
	<?php else : ?>
		<a href="<?php echo esc_url( $video['url'] ); ?>" target="_blank" rel="noopener"><img loading="lazy" src="<?php echo esc_url( $video['image'] ); ?>" alt="<?php echo esc_attr( $video['title'] ); ?>"><span class="play-mark">▶</span></a>
	<?php endif; ?>
	</div><div><small><?php echo esc_html( $video['label'] ); ?></small><h3><?php echo esc_html( $video['title'] ); ?></h3><div class="video-actions"><?php if ( ! empty( $video['video_file'] ) ) : ?><button type="button" class="text-button video-toggle">پخش ویدیو ▶</button><?php endif; ?><a class="text-button" href="<?php echo esc_url( $video['url'] ); ?>" target="_blank" rel="noopener">ریل اصلی ↗</a></div></div></article><?php endforeach; ?></div></section>
	<section class="process section" id="booking"><div class="section-heading"><span class="eyebrow">رزرو آنلاین</span><h2>چهار قدم تا <em>نوبت تو</em></h2></div><div class="steps"><div><span>۱</span><strong>انتخاب خدمت</strong><small>خدمت و متخصص</small></div><div><span>۲</span><strong>انتخاب مدل</strong><small>از بروشور نمونه‌ها</small></div><div><span>۳</span><strong>انتخاب زمان</strong><small>روز و ساعت آزاد</small></div><div><span>۴</span><strong>تأیید نهایی</strong><small>ارسال وضعیت با پیامک</small></div></div><button class="button open-booking">همین حالا رزرو کن</button></section>
	<section class="journal section" id="journal"><div class="section-heading compact"><span class="eyebrow">مجلهٔ زیبایی</span><h2>زیبایی‌نامهٔ <em>میرال</em></h2></div><div class="journal-grid">
	<?php $articles = get_posts( array( 'numberposts' => 3, 'post_status' => 'publish' ) ); if ( $articles ) : foreach ( $articles as $article_index => $article ) : ?><article><img src="<?php echo esc_url( mirall_journal_image( $article, $article_index ) ); ?>" alt="<?php echo esc_attr( get_the_title( $article ) ); ?>"><div><span><?php echo esc_html( get_the_date( '', $article ) ); ?></span><h3><?php echo esc_html( get_the_title( $article ) ); ?></h3><p><?php echo esc_html( wp_trim_words( $article->post_content, 22 ) ); ?></p><a href="<?php echo esc_url( get_permalink( $article ) ); ?>">مطالعه مطلب ←</a></div></article><?php endforeach; else : ?><article><img src="<?php echo mirall_asset( 'journal-color.svg' ); ?>" alt="تصویر شاخص راهنمای رنگ مو"><div><span>راهنمای رنگ مو</span><h3>چطور تناژ مناسب پوستمان را انتخاب کنیم؟</h3><p>سه نکته کاربردی برای انتخاب دقیق‌تر پیش از مشاوره.</p></div></article><article><img src="<?php echo mirall_asset( 'journal-care.svg' ); ?>" alt="تصویر شاخص مراقبت مو"><div><span>مراقبت مو</span><h3>بعد از بالیاژ، مو به چه مراقبتی نیاز دارد؟</h3><p>از شست‌وشوی درست تا فاصله مناسب ترمیم رنگ.</p></div></article><article><img src="<?php echo mirall_asset( 'journal-makeup.svg' ); ?>" alt="تصویر شاخص میکاپ"><div><span>روز مراسم</span><h3>پیش از میکاپ حرفه‌ای چه کارهایی انجام دهیم؟</h3><p>چک‌لیست کوتاه برای پوست آماده و نتیجه ماندگارتر.</p></div></article><?php endif; ?>
	</div></section>
	<?php $reviews = get_posts( array( 'post_type' => 'mirall_review', 'post_status' => 'publish', 'numberposts' => 6, 'orderby' => 'menu_order', 'order' => 'ASC' ) ); if ( $reviews ) : ?><section class="reviews section"><div class="section-heading compact"><span class="eyebrow">از زبان همراهان میرال</span><h2>حس خوبِ <em>اعتماد</em></h2><p>بازخوردهای عمومی و مثبت منتشرشده در صفحه رسمی میرال.</p></div><div class="review-grid"><?php foreach ( $reviews as $review ) : ?><blockquote><span>“</span><p><?php echo esc_html( wp_strip_all_tags( $review->post_content ) ); ?></p><footer><strong><?php echo esc_html( get_post_meta( $review->ID, '_mirall_reviewer', true ) ?: 'همراه میرال' ); ?></strong><small><?php echo esc_html( get_post_meta( $review->ID, '_mirall_review_source', true ) ?: 'اینستاگرام میرال' ); ?></small></footer></blockquote><?php endforeach; ?></div></section><?php endif; ?>
	<section class="contact section" id="contact"><div class="contact-card reveal"><span class="eyebrow">تماس با میرال</span><h2>منتظر دیدنت هستیم</h2><p><?php echo esc_html( mirall_option( 'address', 'تهران، فرشته، مجتمع تجاری داریوش، بلوک B، طبقه ۳، واحد ۲۳۸' ) ); ?></p><div class="contact-lines"><a href="tel:<?php echo esc_attr( mirall_option( 'phone', '02122003932' ) ); ?>"><small>تلفن سالن</small><strong><?php echo esc_html( mirall_option( 'phone', '02122003932' ) ); ?></strong></a><a href="tel:<?php echo esc_attr( mirall_option( 'mobile', '09125707416' ) ); ?>"><small>رزرو و مشاوره</small><strong><?php echo esc_html( mirall_option( 'mobile', '09125707416' ) ); ?></strong></a></div><div class="contact-actions"><button class="button open-booking">رزرو نوبت</button><a class="button button-ghost" href="<?php echo esc_url( mirall_option( 'instagram', 'https://www.instagram.com/mirall_beauty_center/' ) ); ?>" target="_blank" rel="noopener">اینستاگرام میرال</a></div></div><div class="map-card"><span class="map-pin">M</span><div><strong>مجتمع تجاری داریوش</strong><small>خیابان فرشته، تهران</small></div><a href="https://www.google.com/maps/search/?api=1&query=%D9%85%D8%AC%D8%AA%D9%85%D8%B9+%D8%AA%D8%AC%D8%A7%D8%B1%DB%8C+%D8%AF%D8%A7%D8%B1%DB%8C%D9%88%D8%B4+%D9%81%D8%B1%D8%B4%D8%AA%D9%87" target="_blank" rel="noopener">مسیریابی روی نقشه ←</a></div></section>
</main>
<dialog class="lightbox" id="lightbox"><button aria-label="بستن">×</button><img alt=""><strong></strong></dialog>
<?php get_footer(); ?>
