<?php
/* Template Name: تماس با میرال */
get_header();
?>
<main id="main">
	<section class="inner-hero" style="--inner-bg:url('<?php echo mirall_asset( 'makeup.jpg' ); ?>')"><div><span class="eyebrow">CONTACT MIRALL</span><h1>با میرال در ارتباط باش</h1><p>برای مشاوره، رزرو و پیگیری نوبت از راه‌های زیر با مجموعه تماس بگیر.</p></div></section>
	<section class="inner-content contact-page-grid"><div class="contact-card"><span class="eyebrow">اطلاعات تماس</span><h2>منتظر دیدنت هستیم</h2><p><?php echo esc_html( mirall_option( 'address', 'تهران، فرشته، مجتمع تجاری داریوش، بلوک B، طبقه ۳، واحد ۲۳۸' ) ); ?></p><div class="contact-lines"><a href="tel:<?php echo esc_attr( mirall_option( 'phone', '02122003932' ) ); ?>"><small>تلفن سالن</small><strong><?php echo esc_html( mirall_option( 'phone', '02122003932' ) ); ?></strong></a><a href="tel:<?php echo esc_attr( mirall_option( 'mobile', '09125707416' ) ); ?>"><small>رزرو و مشاوره</small><strong><?php echo esc_html( mirall_option( 'mobile', '09125707416' ) ); ?></strong></a></div><div class="detail-list light"><span>پشتیبانی رزرو و پیگیری</span><span>پاسخ‌گویی تلفنی مجموعه</span><span>دسترسی از خیابان فرشته</span></div><button class="button open-booking">رزرو نوبت</button></div><div class="contact-visual"><iframe class="contact-map" src="<?php echo esc_url( mirall_map_embed_url() ); ?>" title="نقشه مجتمع تجاری داریوش، فرشته" loading="lazy" allowfullscreen referrerpolicy="no-referrer-when-downgrade"></iframe><div class="map-card map-card-overlay"><span class="map-pin" aria-hidden="true">⌖</span><div><strong>مجتمع تجاری داریوش</strong><small>خیابان فرشته، تهران</small></div><a href="https://www.google.com/maps/search/?api=1&query=%D9%85%D8%AC%D8%AA%D9%85+%D8%AA%D8%AC%D8%A7%D8%B1%DB%8C+%D8%AF%D8%A7%D8%B1%DB%8C%D9%88%D8%B4+%D9%81%D8%B1%D8%B4%D8%AA%D9%87" target="_blank" rel="noopener">مسیریابی روی نقشه ←</a></div></div></section>
	<section class="inner-content contact-options"><a href="tel:<?php echo esc_attr( mirall_option( 'phone', '02122003932' ) ); ?>" style="--option-bg:url('<?php echo mirall_asset( 'light-ombre.jpg' ); ?>')"><small>تماس مستقیم</small><strong>گفت‌وگو با پذیرش</strong></a><a href="https://wa.me/989125707416" target="_blank" rel="noopener" style="--option-bg:url('<?php echo mirall_asset( 'balayage-warm.jpg' ); ?>')"><small>پیام‌رسان</small><strong>واتس‌اپ مجموعه</strong></a><a href="https://www.instagram.com/mirall_beauty_center/" target="_blank" rel="noopener" style="--option-bg:url('<?php echo mirall_asset( 'balayage-girly.jpg' ); ?>')"><small>شبکه اجتماعی</small><strong>اینستاگرام رسمی</strong></a></section>
</main>
<?php get_footer(); ?>
