<?php
/* Template Name: خدمات میرال */
get_header();
?>
<main id="main">
	<section class="inner-hero" style="--inner-bg:url('<?php echo mirall_asset( 'balayage-warm.jpg' ); ?>')"><div><span class="eyebrow">MIRALL SERVICES</span><h1>خدمات زیبایی میرال</h1><p>خدمت دلخواهت را ببین، مدل را انتخاب کن و زمان پیشنهادی را آنلاین ثبت کن.</p></div></section>
	<section class="inner-content"><div class="section-heading compact"><span class="eyebrow">خدمات میرال</span><h2>یک انتخاب دقیق برای <em>هر استایل</em></h2><p>از تغییر رنگ و احیای مو تا میکاپ، ناخن، ابرو و مژه؛ هر مسیر با گفت‌وگو و مشاوره شروع می‌شود.</p></div><?php echo shortcode_exists( 'mirall_services' ) ? do_shortcode( '[mirall_services]' ) : ''; ?></section>
	<section class="inner-content service-showcase"><article><img src="<?php echo mirall_asset( 'balayage-warm.jpg' ); ?>" alt="بالیاژ و رنگ مو میرال"><div><small>COLOR STUDIO</small><h2>رنگ، لایت و مراقبت مو</h2><p>از مشاوره تناژ و تست سلامت مو تا اجرای بالیاژ، آمبره، هایلایت و اصلاح رنگ.</p><button class="text-button open-booking" data-service="رنگ و لایت">انتخاب مدل و رزرو ←</button></div></article><article><img src="<?php echo mirall_asset( 'makeup.jpg' ); ?>" alt="میکاپ حرفه‌ای میرال"><div><small>FACE DESIGN</small><h2>میکاپ و استایل مراسم</h2><p>انتخاب سبک از بروشور و طراحی چهره با توجه به فرم صورت و حال‌وهوای مراسم.</p><button class="text-button open-booking" data-service="میکاپ و عروس">دیدن مدل‌ها و رزرو ←</button></div></article></section>
	<section class="inner-content service-faq"><div class="section-heading compact"><span class="eyebrow">پرسش‌های رایج</span><h2>قبل از رزرو، <em>بدان</em></h2></div><details><summary>آیا پیش از خدمت مشاوره انجام می‌شود؟</summary><p>بله؛ درخواست شما با توجه به خدمت و شرایط مو یا چهره بررسی می‌شود تا انتخاب دقیق‌تری داشته باشید.</p></details><details><summary>اگر خدمت موردنظر را دقیق ندانم چه؟</summary><p>می‌توانید یک مدل از بروشور انتخاب کنید یا در توضیحات رزرو بنویسید که برای انتخاب خدمت به مشاوره نیاز دارید.</p></details><details><summary>قیمت خدمات چطور اعلام می‌شود؟</summary><p>هزینه به شرایط و انتخاب نهایی بستگی دارد؛ برای دریافت مبلغ دقیق، هنگام هماهنگی از پذیرش استعلام بگیرید.</p></details></section>
	<section class="inner-content"><div class="page-cta visual-cta" style="--cta-bg:url('<?php echo mirall_asset( 'light-ombre.jpg' ); ?>')"><div><h2>مدل موردنظرت را از بروشور انتخاب کن</h2><p>سبک دلخواهت را ببین و درخواست رزرو را مستقیم ثبت کن.</p></div><a class="button" href="<?php echo esc_url( home_url( '/beauty-brochure/' ) ); ?>">مشاهده بروشور</a></div></section>
</main>
<?php get_footer(); ?>
