<?php
/* Template Name: درباره میرال */
get_header();
?>
<main id="main">
	<section class="inner-hero" style="--inner-bg:url('<?php echo mirall_asset( 'caramel-highlight.jpg' ); ?>')"><div><span class="eyebrow">ABOUT MIRALL</span><h1>روایت ظریف زیبایی</h1><p>مشاورهٔ دقیق، اجرای حرفه‌ای و انتخابی هماهنگ با چهره، سبک شخصی و سلامت مو.</p></div></section>
	<section class="inner-content inner-grid"><div class="story-collage"><img src="<?php echo mirall_asset( 'balayage-warm.jpg' ); ?>" alt="نمونه رنگ و لایت مرکز زیبایی میرال"><img src="<?php echo mirall_asset( 'makeup.jpg' ); ?>" alt="نمونه میکاپ میرال"></div><div class="inner-copy"><span class="eyebrow">میرال در فرشته</span><h2>زیبایی وقتی ماندگار است که <em>شبیه خودت</em> بماند</h2><p>در میرال هر خدمت از گفت‌وگو و مشاوره شروع می‌شود. فرم چهره، تناژ پوست، سلامت مو و نتیجهٔ مورد انتظار کنار هم دیده می‌شوند تا انتخاب نهایی فقط زیبا نباشد؛ مناسب تو هم باشد.</p><p>نمونه‌های واقعی، مدل‌های قابل انتخاب و مراحل شفاف رزرو کمک می‌کنند پیش از مراجعه تصویر روشن‌تری از نتیجه داشته باشی.</p><div class="detail-list"><span>مشاورهٔ پیش از اجرا</span><span>انتخاب مدل از بروشور</span><span>پیگیری وضعیت نوبت</span></div><button class="button open-booking">رزرو مشاوره</button></div></section>
	<section class="inner-content values-section"><div class="section-heading compact"><span class="eyebrow">استاندارد تجربهٔ میرال</span><h2>از ایده تا نتیجه، <em>شفاف و شخصی</em></h2></div><div class="image-values"><article style="--card-bg:url('<?php echo mirall_asset( 'light-ombre.jpg' ); ?>')"><strong>انتخاب آگاهانه</strong><p>دیدن مدل، توضیح شرایط مو و گفت‌وگو پیش از تأیید نوبت.</p></article><article style="--card-bg:url('<?php echo mirall_asset( 'caramel-highlight.jpg' ); ?>')"><strong>اجرای هماهنگ</strong><p>انتخاب تناژ و فرم متناسب با چهره و سبک زندگی.</p></article><article style="--card-bg:url('<?php echo mirall_asset( 'balayage-girly.jpg' ); ?>')"><strong>مراقبت پس از خدمت</strong><p>راهنمای مراقبت برای ماندگاری بهتر نتیجه.</p></article></div></section>
	<section class="inner-content"><div class="page-cta visual-cta" style="--cta-bg:url('<?php echo mirall_asset( 'makeup.jpg' ); ?>')"><div><span class="eyebrow">MIRALL BEAUTY</span><h2>وقت تغییر دلخواهت رسیده؟</h2><p>مدل را ببین، خدمت را انتخاب کن و درخواستت را ثبت کن.</p></div><button class="button open-booking">شروع رزرو آنلاین</button></div></section>
</main>
<?php get_footer(); ?>
